import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16">
      <Link href="/scout" className="block mb-10">
        <span className="text-xl font-bold">
          <span className="text-emerald-400">JobScout</span>{" "}
          <span className="text-zinc-400 font-normal">AI</span>
        </span>
      </Link>

      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>

      <div className="space-y-6 text-zinc-300 text-sm leading-relaxed">
        <p className="text-zinc-400">Last updated: March 2026</p>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">
            The service
          </h2>
          <p>
            JobScout AI is a subscription service that uses artificial
            intelligence to scan job boards, match postings to your profile, and
            draft application pitches. Digests are delivered via email.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">
            Free trial & billing
          </h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>New accounts receive a 7-day free trial with full access.</li>
            <li>
              After the trial, continued access requires a subscription at
              $29/month.
            </li>
            <li>
              Billing is handled by Stripe. You can cancel anytime from your
              dashboard.
            </li>
            <li>
              No refunds for partial months, but cancellation takes effect
              immediately at the end of the current billing period.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">
            AI-generated content
          </h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>
              Job matches and pitch drafts are generated by AI and may contain
              inaccuracies.
            </li>
            <li>
              Always review and customize pitches before sending them to
              employers.
            </li>
            <li>
              We do not guarantee job placement or interview outcomes.
            </li>
            <li>
              Job listings are scraped from public sources — we are not
              affiliated with any employer or job board.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">
            Your responsibilities
          </h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>
              Provide accurate resume and profile information for the best
              results.
            </li>
            <li>
              Do not use the service for spam, harassment, or any illegal
              purpose.
            </li>
            <li>
              One account per person. Do not share account credentials.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">
            Limitations
          </h2>
          <p>
            The service is provided &quot;as is.&quot; We make no warranties
            about uptime, accuracy of job matches, or suitability of AI-drafted
            content. Our total liability is limited to the amount you&apos;ve
            paid in the last 3 months.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">Changes</h2>
          <p>
            We may update these terms. Continued use after changes constitutes
            acceptance. Material changes will be communicated via email.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-3">Contact</h2>
          <p>
            Questions? Email{" "}
            <a
              href="mailto:support@jobscoutai.com"
              className="text-emerald-400 hover:text-emerald-300"
            >
              support@jobscoutai.com
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
